//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientTest.ServiceReferenceYum {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Custumer", Namespace="http://br.pucminas/")]
    [System.SerializableAttribute()]
    public partial class Custumer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoCompletoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cpf {
            get {
                return this.CpfField;
            }
            set {
                if ((object.ReferenceEquals(this.CpfField, value) != true)) {
                    this.CpfField = value;
                    this.RaisePropertyChanged("Cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EnderecoCompleto {
            get {
                return this.EnderecoCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoCompletoField, value) != true)) {
                    this.EnderecoCompletoField = value;
                    this.RaisePropertyChanged("EnderecoCompleto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://br.pucminas/", ConfigurationName="ServiceReferenceYum.YUMServiceSoap")]
    public interface YUMServiceSoap {
        
        // CODEGEN: Generating message contract since element name cpf from namespace http://br.pucminas/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://br.pucminas/GetCustomerByCPF", ReplyAction="*")]
        ClientTest.ServiceReferenceYum.GetCustomerByCPFResponse GetCustomerByCPF(ClientTest.ServiceReferenceYum.GetCustomerByCPFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://br.pucminas/GetCustomerByCPF", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientTest.ServiceReferenceYum.GetCustomerByCPFResponse> GetCustomerByCPFAsync(ClientTest.ServiceReferenceYum.GetCustomerByCPFRequest request);
        
        // CODEGEN: Generating message contract since element name customer from namespace http://br.pucminas/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://br.pucminas/UpdateCustomer", ReplyAction="*")]
        ClientTest.ServiceReferenceYum.UpdateCustomerResponse UpdateCustomer(ClientTest.ServiceReferenceYum.UpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://br.pucminas/UpdateCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientTest.ServiceReferenceYum.UpdateCustomerResponse> UpdateCustomerAsync(ClientTest.ServiceReferenceYum.UpdateCustomerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerByCPFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerByCPF", Namespace="http://br.pucminas/", Order=0)]
        public ClientTest.ServiceReferenceYum.GetCustomerByCPFRequestBody Body;
        
        public GetCustomerByCPFRequest() {
        }
        
        public GetCustomerByCPFRequest(ClientTest.ServiceReferenceYum.GetCustomerByCPFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://br.pucminas/")]
    public partial class GetCustomerByCPFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cpf;
        
        public GetCustomerByCPFRequestBody() {
        }
        
        public GetCustomerByCPFRequestBody(string cpf) {
            this.cpf = cpf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerByCPFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerByCPFResponse", Namespace="http://br.pucminas/", Order=0)]
        public ClientTest.ServiceReferenceYum.GetCustomerByCPFResponseBody Body;
        
        public GetCustomerByCPFResponse() {
        }
        
        public GetCustomerByCPFResponse(ClientTest.ServiceReferenceYum.GetCustomerByCPFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://br.pucminas/")]
    public partial class GetCustomerByCPFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientTest.ServiceReferenceYum.Custumer GetCustomerByCPFResult;
        
        public GetCustomerByCPFResponseBody() {
        }
        
        public GetCustomerByCPFResponseBody(ClientTest.ServiceReferenceYum.Custumer GetCustomerByCPFResult) {
            this.GetCustomerByCPFResult = GetCustomerByCPFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomer", Namespace="http://br.pucminas/", Order=0)]
        public ClientTest.ServiceReferenceYum.UpdateCustomerRequestBody Body;
        
        public UpdateCustomerRequest() {
        }
        
        public UpdateCustomerRequest(ClientTest.ServiceReferenceYum.UpdateCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://br.pucminas/")]
    public partial class UpdateCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientTest.ServiceReferenceYum.Custumer customer;
        
        public UpdateCustomerRequestBody() {
        }
        
        public UpdateCustomerRequestBody(ClientTest.ServiceReferenceYum.Custumer customer) {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomerResponse", Namespace="http://br.pucminas/", Order=0)]
        public ClientTest.ServiceReferenceYum.UpdateCustomerResponseBody Body;
        
        public UpdateCustomerResponse() {
        }
        
        public UpdateCustomerResponse(ClientTest.ServiceReferenceYum.UpdateCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://br.pucminas/")]
    public partial class UpdateCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateCustomerResult;
        
        public UpdateCustomerResponseBody() {
        }
        
        public UpdateCustomerResponseBody(bool UpdateCustomerResult) {
            this.UpdateCustomerResult = UpdateCustomerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface YUMServiceSoapChannel : ClientTest.ServiceReferenceYum.YUMServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class YUMServiceSoapClient : System.ServiceModel.ClientBase<ClientTest.ServiceReferenceYum.YUMServiceSoap>, ClientTest.ServiceReferenceYum.YUMServiceSoap {
        
        public YUMServiceSoapClient() {
        }
        
        public YUMServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public YUMServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YUMServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YUMServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientTest.ServiceReferenceYum.GetCustomerByCPFResponse ClientTest.ServiceReferenceYum.YUMServiceSoap.GetCustomerByCPF(ClientTest.ServiceReferenceYum.GetCustomerByCPFRequest request) {
            return base.Channel.GetCustomerByCPF(request);
        }
        
        public ClientTest.ServiceReferenceYum.Custumer GetCustomerByCPF(string cpf) {
            ClientTest.ServiceReferenceYum.GetCustomerByCPFRequest inValue = new ClientTest.ServiceReferenceYum.GetCustomerByCPFRequest();
            inValue.Body = new ClientTest.ServiceReferenceYum.GetCustomerByCPFRequestBody();
            inValue.Body.cpf = cpf;
            ClientTest.ServiceReferenceYum.GetCustomerByCPFResponse retVal = ((ClientTest.ServiceReferenceYum.YUMServiceSoap)(this)).GetCustomerByCPF(inValue);
            return retVal.Body.GetCustomerByCPFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientTest.ServiceReferenceYum.GetCustomerByCPFResponse> ClientTest.ServiceReferenceYum.YUMServiceSoap.GetCustomerByCPFAsync(ClientTest.ServiceReferenceYum.GetCustomerByCPFRequest request) {
            return base.Channel.GetCustomerByCPFAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientTest.ServiceReferenceYum.GetCustomerByCPFResponse> GetCustomerByCPFAsync(string cpf) {
            ClientTest.ServiceReferenceYum.GetCustomerByCPFRequest inValue = new ClientTest.ServiceReferenceYum.GetCustomerByCPFRequest();
            inValue.Body = new ClientTest.ServiceReferenceYum.GetCustomerByCPFRequestBody();
            inValue.Body.cpf = cpf;
            return ((ClientTest.ServiceReferenceYum.YUMServiceSoap)(this)).GetCustomerByCPFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientTest.ServiceReferenceYum.UpdateCustomerResponse ClientTest.ServiceReferenceYum.YUMServiceSoap.UpdateCustomer(ClientTest.ServiceReferenceYum.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomer(request);
        }
        
        public bool UpdateCustomer(ClientTest.ServiceReferenceYum.Custumer customer) {
            ClientTest.ServiceReferenceYum.UpdateCustomerRequest inValue = new ClientTest.ServiceReferenceYum.UpdateCustomerRequest();
            inValue.Body = new ClientTest.ServiceReferenceYum.UpdateCustomerRequestBody();
            inValue.Body.customer = customer;
            ClientTest.ServiceReferenceYum.UpdateCustomerResponse retVal = ((ClientTest.ServiceReferenceYum.YUMServiceSoap)(this)).UpdateCustomer(inValue);
            return retVal.Body.UpdateCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientTest.ServiceReferenceYum.UpdateCustomerResponse> ClientTest.ServiceReferenceYum.YUMServiceSoap.UpdateCustomerAsync(ClientTest.ServiceReferenceYum.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientTest.ServiceReferenceYum.UpdateCustomerResponse> UpdateCustomerAsync(ClientTest.ServiceReferenceYum.Custumer customer) {
            ClientTest.ServiceReferenceYum.UpdateCustomerRequest inValue = new ClientTest.ServiceReferenceYum.UpdateCustomerRequest();
            inValue.Body = new ClientTest.ServiceReferenceYum.UpdateCustomerRequestBody();
            inValue.Body.customer = customer;
            return ((ClientTest.ServiceReferenceYum.YUMServiceSoap)(this)).UpdateCustomerAsync(inValue);
        }
    }
}
